Add Aggregation Type method in the UI
keitaroinc/ckanext-visualize pull request #31
Opened 2019-12-04 12:45 UTC by miroslavgruevski

2019-12-04 21:52 UTC, klikstermkd requested changes
The placement and the design of the Aggregation type looks good, but the chart type image is squashed on viewport <992px.

![Screenshot (1)](https://user-images.githubusercontent.com/520213/70184697-a5511680-16e8-11ea-90d3-5b5a6a649eab.png)

2019-12-05 08:51 UTC, gocemitevski commented
@klikstermkd pull the latest changes and test again.

2019-12-05 09:32 UTC, klikstermkd commented
@gocemitevski There are still issues with the chart image on mobile viewport as seen in the screenshot.

![localhost_5000_dataset_test-dataset_resource_dd27c7ca-3cb3-42c3-8b1a-70b70ad28349_view_id=66b93a5b-6b5b-495e-bc9b-a2c31a257e51(Pixel 2 XL)](https://user-images.githubusercontent.com/520213/70222479-6eabe800-174a-11ea-822b-4b9e01954640.png)

2019-12-05 09:37 UTC, klikstermkd approved these changes

2019-12-05 09:37 UTC, merged